#!/usr/bin/env python3
"""Build the runtime source bundle and keep its stamp honest.

The menu used to download every file in the manifest one HTTP GET at a time.
This step packs those files into `dist/bundle.luau` as `{path → source}` and
writes a content stamp that both the runtime and the gate share.

  python3 tools/bundle.py          write dist/bundle.luau and stamp the shell
  python3 tools/bundle.py --check  fail if the committed bundle/stamp is stale

The gate has to fail when the bundle does not match the sources. A stale
bundle serving old code while the repo says otherwise is exactly the class of
silent rot this exists to prevent.
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "src" / "core" / "Manifest.luau"
SHELL = ROOT / "ARandomMenu.luau"
DIST = ROOT / "dist"
BUNDLE = DIST / "bundle.luau"
STAMP_PATTERN = re.compile(
    r'(local SOURCE_STAMP: string = )"[0-9a-fA-F]*"'
)


def manifest_paths() -> list[str]:
    text = MANIFEST.read_text(encoding="utf-8")
    paths = ["src/core/Manifest.luau"]
    seen = set(paths)
    for path in re.findall(r'"src/[^"]+\.luau"', text):
        path = path.strip('"')
        if path not in seen:
            seen.add(path)
            paths.append(path)
    return paths


def file_digest(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def compute_stamp(paths: list[str]) -> str:
    hasher = hashlib.sha256()
    for relative in paths:
        payload = (ROOT / relative).read_bytes()
        hasher.update(relative.encode("utf-8"))
        hasher.update(b"\0")
        hasher.update(payload)
        hasher.update(b"\0")
    return hasher.hexdigest()[:16]


def long_string(source: str) -> str:
    equals = 5
    while True:
        open_token = "[" + ("=" * equals) + "["
        close_token = "]" + ("=" * equals) + "]"
        if open_token not in source and close_token not in source:
            return open_token + source + close_token
        equals += 1


def render_bundle(stamp: str, paths: list[str]) -> str:
    entries = []
    for relative in paths:
        source = (ROOT / relative).read_text(encoding="utf-8")
        entries.append(f'        ["{relative}"] = {long_string(source)},')
    body = "\n".join(entries)
    return (
        "--!strict\n"
        "-- Generated by tools/bundle.py. Do not edit by hand.\n"
        "-- The stamp is a digest of every packed file; the runtime refuses\n"
        "-- the bundle when it does not match SOURCE_STAMP in ARandomMenu.luau.\n"
        "return {\n"
        f'    stamp = "{stamp}",\n'
        "    files = {\n"
        f"{body}\n"
        "    },\n"
        "}\n"
    )


def current_shell_stamp() -> str | None:
    match = STAMP_PATTERN.search(SHELL.read_text(encoding="utf-8"))
    if not match:
        return None
    quoted = re.search(r'"([0-9a-fA-F]*)"', match.group(0))
    return quoted.group(1) if quoted else None


def write_shell_stamp(stamp: str) -> None:
    text = SHELL.read_text(encoding="utf-8")
    if not STAMP_PATTERN.search(text):
        raise SystemExit("SOURCE_STAMP is missing from ARandomMenu.luau")
    SHELL.write_text(
        STAMP_PATTERN.sub(rf'\1"{stamp}"', text, count=1),
        encoding="utf-8",
    )


def current_bundle_stamp() -> str | None:
    if not BUNDLE.is_file():
        return None
    match = re.search(r'stamp = "([0-9a-fA-F]+)"', BUNDLE.read_text(encoding="utf-8"))
    return match.group(1) if match else None


def build() -> str:
    paths = manifest_paths()
    missing = [path for path in paths if not (ROOT / path).is_file()]
    if missing:
        raise SystemExit("bundle sources missing:\n  " + "\n  ".join(missing))
    stamp = compute_stamp(paths)
    DIST.mkdir(exist_ok=True)
    BUNDLE.write_text(render_bundle(stamp, paths), encoding="utf-8")
    write_shell_stamp(stamp)
    print(f"bundle {len(paths)} files · stamp {stamp} · {BUNDLE.stat().st_size} bytes")
    return stamp


def check() -> int:
    paths = manifest_paths()
    missing = [path for path in paths if not (ROOT / path).is_file()]
    if missing:
        print("bundle sources missing:\n  " + "\n  ".join(missing))
        return 1
    expected = compute_stamp(paths)
    failures: list[str] = []
    shell_stamp = current_shell_stamp()
    bundle_stamp = current_bundle_stamp()
    if shell_stamp != expected:
        failures.append(
            f"ARandomMenu.luau SOURCE_STAMP is {shell_stamp!r}, expected {expected!r}"
        )
    if bundle_stamp != expected:
        failures.append(
            f"dist/bundle.luau stamp is {bundle_stamp!r}, expected {expected!r}"
        )
    if not BUNDLE.is_file():
        failures.append("dist/bundle.luau is missing")
    elif BUNDLE.is_file():
        packed = set(re.findall(r'\["(src/[^"]+\.luau)"\]', BUNDLE.read_text(encoding="utf-8")))
        wanted = set(paths)
        if packed != wanted:
            extra = packed - wanted
            absent = wanted - packed
            if extra:
                failures.append("bundle has extra files: " + ", ".join(sorted(extra)))
            if absent:
                failures.append("bundle is missing files: " + ", ".join(sorted(absent)))
    if failures:
        for line in failures:
            print("  " + line)
        print("run: python3 tools/bundle.py")
        return 1
    print(f"ok · stamp {expected} · {len(paths)} files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check()
    build()
    return 0


if __name__ == "__main__":
    sys.exit(main())
